include ../makefile_defines.txt

COMPONENT_NAME = m2mtimerimpl_linux_unit
SRC_FILES = \
        ../../../../lwm2m-client-linux/source/m2mtimerimpl.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/common_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/threadhelper_stub.cpp \
        m2mtimerimpl_linuxtest.cpp \
        test_m2mtimerimpl_linux.cpp


include ../MakefileWorker.mk

