include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionhandler_mbed_unit
SRC_FILES = \
        ../../../../../lwm2m-client-mbed/source/m2mconnectionhandler.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mconnectionhandler_mbedtest.cpp \
        test_m2mconnectionhandler_mbed.cpp \
       ../stub/common_stub.cpp \
       ../stub/nsdlaccesshelper_stub.cpp \
       ../stub/m2mstring_stub.cpp \
       ../stub/m2mconnectionsecurity_stub.cpp \
       ../stub/m2mconnectionhandlerpimpl_stub.cpp \

include ../MakefileWorker.mk

