include ../makefile_defines.txt

COMPONENT_NAME = m2mtimerimpl_mbed_unit
SRC_FILES = \
        ../../../../lwm2m-client-mbed/source/m2mtimerimpl.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/common_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        m2mtimerimpl_mbedtest.cpp \
        test_m2mtimerimpl_mbed.cpp


include ../MakefileWorker.mk

