include ../makefile_defines.txt

COMPONENT_NAME = m2mobject_unit
SRC_FILES = \
        ../../../../source/m2mobject.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mresourceinstance_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2mtlvserializer_stub.cpp \
        ../stub/m2mtlvdeserializer_stub.cpp \
        ../stub/m2mreporthandler_stub.cpp \
        ../stub/common_stub.cpp \
        ../stub/m2mstring_stub.cpp \
	m2mobjecttest.cpp \
        test_m2mobject.cpp


include ../MakefileWorker.mk

