include ../makefile_defines.txt

COMPONENT_NAME = m2mtimer_unit
SRC_FILES = \
        ../../../../source/m2mtimer.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mtimerimpl_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        m2mtimertest.cpp \
        test_m2mtimer.cpp


include ../MakefileWorker.mk

