include ../makefile_defines.txt

COMPONENT_NAME = m2mbase_unit
SRC_FILES = \
        ../../../../source/m2mbase.cpp \
	../../../../source/m2mconstants.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mreporthandler_stub.cpp \
        ../stub/m2mstring_stub.cpp \
	m2mbasetest.cpp \
        test_m2mbase.cpp


include ../MakefileWorker.mk

