include ../makefile_defines.txt

COMPONENT_NAME = m2mtimerpimpl_mbed_unit
SRC_FILES = \
        ../../../../../lwm2m-client-mbed/source/m2mtimerpimpl.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mtimerpimpl_mbedtest.cpp \
        test_m2mtimerpimpl_mbed.cpp \
        ../stub/common_stub.cpp \
        ../stub/m2mstring_stub.cpp \


include ../MakefileWorker.mk

