include ../makefile_defines.txt

COMPONENT_NAME = m2mresourceinstance_unit
SRC_FILES = \
        ../../../../source/m2mresourceinstance.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/m2mtimer_stub.cpp \
        ../stub/m2mreporthandler_stub.cpp \
        ../stub/common_stub.cpp \
	m2mresourceinstancetest.cpp \
        test_m2mresourceinstance.cpp


include ../MakefileWorker.mk

