include ../makefile_defines.txt

COMPONENT_NAME = m2mresource_unit
SRC_FILES = \
        ../../../../source/m2mresource.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/m2mtimer_stub.cpp \
        ../stub/m2mreporthandler_stub.cpp \
        ../stub/m2mresourceinstance_stub.cpp \
	m2mresourcetest.cpp \
        test_m2mresource.cpp


include ../MakefileWorker.mk

