include ../makefile_defines.txt

COMPONENT_NAME = m2mstring_unit
SRC_FILES = \
	../../../../source/m2mstring.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mstringtest.cpp \
        test_m2mstring.cpp


include ../MakefileWorker.mk

