include ../makefile_defines.txt

COMPONENT_NAME = threadhelper_unit
SRC_FILES = \
        ../../../../../lwm2m-client-linux/source/threadhelper.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/common_stub.cpp \
        threadhelpertest.cpp \
        test_threadhelper.cpp


include ../MakefileWorker.mk

