include ../makefile_defines.txt

COMPONENT_NAME = m2mfirmware_unit
SRC_FILES = \
        ../../../../source/m2mfirmware.cpp \
	../../../../source/m2mconstants.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mobject_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mresourceinstance_stub.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mstring_stub.cpp \
	m2mfirmwaretest.cpp \
        test_m2mfirmware.cpp


include ../MakefileWorker.mk

