include ../makefile_defines.txt

COMPONENT_NAME = nsdlaccesshelper_unit
SRC_FILES = \
	../../../../source/nsdlaccesshelper.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/common_stub.cpp \
        ../stub/m2mnsdlinterface_stub.cpp \
	nsdlaccesshelpertest.cpp \
        test_nsdlaccesshelper.cpp


include ../MakefileWorker.mk

