include ../makefile_defines.txt

COMPONENT_NAME = m2mreporthandler_unit
SRC_FILES = \
        ../../../../source/m2mreporthandler.cpp \
	../../../../source/m2mconstants.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mtimer_stub.cpp \
        ../stub/m2mstring_stub.cpp \
	m2mreporthandlertest.cpp \
        test_m2mreporthandler.cpp


include ../MakefileWorker.mk

