include ../makefile_defines.txt

COMPONENT_NAME = m2mtlvdeserializer_unit
SRC_FILES = \
        ../../../../source/m2mtlvdeserializer.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mresourceinstance_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2mobject_stub.cpp \
        ../../../../source/m2mtlvdeserializer.cpp \
	m2mtlvdeserializertest.cpp \
        test_m2mtlvdeserializer.cpp


include ../MakefileWorker.mk

