include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionhandlerimpl_mbed_unit
SRC_FILES = \
        ../../../../../lwm2m-client-mbed/source/m2mconnectionhandlerpimpl.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mconnectionhandlerpimpl_mbedtest.cpp \
        test_m2mconnectionhandlerpimpl_mbed.cpp \
       ../stub/m2mconnectionhandler_stub.cpp \
       ../stub/common_stub.cpp \
       ../stub/nsdlaccesshelper_stub.cpp \
       ../stub/m2mstring_stub.cpp \
       ../stub/m2mconnectionsecurity_stub.cpp \
       ../stub/m2msecurity_stub.cpp \
       ../stub/m2mbase_stub.cpp \
       ../stub/m2mobject_stub.cpp \


include ../MakefileWorker.mk

