include ../makefile_defines.txt

COMPONENT_NAME = m2mtimer_linux_unit
SRC_FILES = \
        ../../../../../lwm2m-client-linux/source/m2mtimer.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mtimertest.cpp \
        test_m2mtimer.cpp \
        ../stub/m2mtimerpimpl_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/threadhelper_stub.cpp \


include ../MakefileWorker.mk

