include ../makefile_defines.txt

COMPONENT_NAME = m2mdevice_unit
SRC_FILES = \
        ../../../../source/m2mdevice.cpp \
	../../../../source/m2mconstants.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mobject_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mstring_stub.cpp \
	m2mdevicetest.cpp \
        test_m2mdevice.cpp


include ../MakefileWorker.mk

