include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionhandlerpimpl_linux_unit
SRC_FILES = \
        ../../../../../lwm2m-client-linux/source/m2mconnectionhandlerpimpl.cpp \
        ../../../../../lwm2m-client-linux/source/connthreadhelper.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mconnectionhandlerpimpl_linuxtest.cpp \
        test_m2mconnectionhandlerpimpl_linux.cpp \
       ../stub/common_stub.cpp \
       ../stub/nsdlaccesshelper_stub.cpp \
       ../stub/m2msecurity_stub.cpp \
       ../stub/m2mconnectionsecurity_stub.cpp \
       ../stub/m2mstring_stub.cpp \
       ../stub/m2mobject_stub.cpp \
       ../stub/m2mresource_stub.cpp \
       ../stub/m2mresourceinstance_stub.cpp \
       ../stub/m2mbase_stub.cpp \
       ../stub/m2mconnectionsecurity_stub.cpp \



include ../MakefileWorker.mk

