include ../makefile_defines.txt

COMPONENT_NAME = m2mobjectinstance_unit
SRC_FILES = \
        ../../../../source/m2mobjectinstance.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mresourceinstance_stub.cpp \
        ../stub/common_stub.cpp \
        ../stub/m2mtlvserializer_stub.cpp \
        ../stub/m2mtlvdeserializer_stub.cpp \
        ../stub/m2mstring_stub.cpp \
	m2mobjectinstancetest.cpp \
        test_m2mobjectinstance.cpp


include ../MakefileWorker.mk

