include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionhandlerimpl_linux_unit
SRC_FILES = \
        ../../../../lwm2m-client-linux/source/m2mconnectionhandlerimpl.cpp \
        ../../../../lwm2m-client-linux/source/connthreadhelper.cpp

TEST_SRC_FILES = \
	main.cpp \
       ../stub/common_stub.cpp \
       ../stub/nsdlaccesshelper_stub.cpp \
       ../stub/m2mstring_stub.cpp \
        m2mconnectionhandlerimpl_linuxtest.cpp \
        test_m2mconnectionhandlerimpl_linux.cpp


include ../MakefileWorker.mk

