include ../makefile_defines.txt

COMPONENT_NAME = m2mtlvserializer_unit
SRC_FILES = \
        ../../../../source/m2mtlvserializer.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mresourceinstance_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2mobject_stub.cpp \
	m2mtlvserializertest.cpp \
        test_m2mtlvserializer.cpp


include ../MakefileWorker.mk

