include ../makefile_defines.txt

COMPONENT_NAME = m2minterfaceimpl_unit
SRC_FILES = \
        ../../../../source/m2minterfaceimpl.cpp \
	../../../../source/m2mconstants.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mobject_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2msecurity_stub.cpp \
        ../stub/m2mtimer_stub.cpp \
        ../stub/m2mnsdlinterface_stub.cpp \
        ../stub/m2mconnectionhandler_stub.cpp \
        ../stub/m2mconnectionsecurity_stub.cpp \
        ../stub/m2mconnectionhandlerfactory_stub.cpp \
	m2minterfaceimpltest.cpp \
        test_m2minterfaceimpl.cpp


include ../MakefileWorker.mk

