include ../makefile_defines.txt

COMPONENT_NAME = m2mtimerimpl_linux_unit
SRC_FILES = \
        ../../../../../lwm2m-client-linux/source/m2mtimerpimpl.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mtimerpimpl_linuxtest.cpp \
        test_m2mtimerpimpl_linux.cpp \
        ../stub/common_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/threadhelper_stub.cpp \


include ../MakefileWorker.mk

