include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionhandlerimpl_mbed_unit
SRC_FILES = \
        ../../../../lwm2m-client-mbed/source/m2mconnectionhandlerimpl.cpp

TEST_SRC_FILES = \
	main.cpp \
       ../stub/common_stub.cpp \
       ../stub/nsdlaccesshelper_stub.cpp \
       ../stub/m2mstring_stub.cpp \
        m2mconnectionhandlerimpl_mbedtest.cpp \
        test_m2mconnectionhandlerimpl_mbed.cpp


include ../MakefileWorker.mk

