include ../makefile_defines.txt

COMPONENT_NAME = m2msecurity_unit
SRC_FILES = \
        ../../../../source/m2msecurity.cpp \
	../../../../source/m2mconstants.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mobject_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mbase_stub.cpp \
	m2msecuritytest.cpp \
        test_m2msecurity.cpp


include ../MakefileWorker.mk

