include ../makefile_defines.txt

COMPONENT_NAME = m2minterfacefactory_unit
SRC_FILES = \
        ../../../../source/m2minterfacefactory.cpp

TEST_SRC_FILES = \
	main.cpp \
        ../stub/m2mobject_stub.cpp \
        ../stub/m2mbase_stub.cpp \
        ../stub/m2mresource_stub.cpp \
        ../stub/m2mresourceinstance_stub.cpp \
        ../stub/m2mstring_stub.cpp \
        ../stub/m2mobjectinstance_stub.cpp \
        ../stub/m2mdevice_stub.cpp \
        ../stub/m2mfirmware_stub.cpp \
        ../stub/m2msecurity_stub.cpp \
        ../stub/m2mserver_stub.cpp \
        ../stub/m2minterfaceimpl_stub.cpp \
	m2minterfacefactorytest.cpp \
        test_m2minterfacefactory.cpp


include ../MakefileWorker.mk

